### PR TITLE
Add teamcity reporter

### PR DESCRIPTION
**Pull request by jbryson3**
The tap reporter has become a bit of a pain for us, now that we've upgraded to Teamcity 9.  I added a teamcity reporter and tested it with our stack. It's pretty basic, but should be a good starting point for us and others.

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Restarted windows ci.

**Comment by johanneswuerbach** [comment]
Could you add the reporter the README?

**Comment by jbryson3** [comment]
Good catch, I knew I forgot to do something.  I added sample output to the README as well. Not sure if that's helpful since it should just plugin to Teamcity's api.  I bumped the version as well, I never know whether to do that for a pull request or not.  I tried to break up the commits so you could selectively pull what you wanted. Thanks!

**Comment by johanneswuerbach** [comment]
Thank you, version bumping shouldn't be done in PRs (here), otherwise LGTM. Could you remove the bump commit?

**Comment by jbryson3** [comment]
Just reverted it, thanks for the guidance.

**Comment by johanneswuerbach** [comment]
I created another PR without the two version bump and revert commits, going to merge when CI is green. :smile:

**Comment by jbryson3** [comment]
/smackshead - should've thought to create a new PR instead of dirtying the history with a revert commit!

**Comment by johanneswuerbach** [comment]
No worries, in the future you can also do an interactive rebase and force push to a PR.

**Pull request closed without merging**
