### PR TITLE
Use published socket.io without native dependencies

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Fixes https://github.com/airportyh/testem/issues/659, fixes https://github.com/airportyh/testem/issues/660

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Working on linking the pure packages together.

**Comment by stefanpenner** [comment]
engine.io-client-pure released

**Comment by johanneswuerbach** [comment]
Sorry, but for some reason testem websocket connections aren't working when using the pure version. I'll revert the git dependencies for now and look into that tomorrow again.

WDYT?

**Comment by stefanpenner** [comment]
@johanneswuerbach keep me posted. I'll take a look tonight aswell

**Comment by johanneswuerbach** [comment]
After npm link-ing all pure packages locally and running `make build` in both clients I still see `Uncaught Error: Cannot find module 'buffer'` from `socket.io.js` when opening a browser with testem.

**Comment by johanneswuerbach** [comment]
:tada: now everything passes. Sorry about the versioning mess, I'll clean this up tmrw.

**Pull request merged**
