### PR TITLE
WIP: Windows and PhantomJS 2.0

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Chocolatey is installing PhantomJS now inside %PATH%

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
The issue is that chocolatey is using a shim now to exec phantomjs. After testem received all test results from PhantomJS, it tries to kill the process, but only has the PID of the shim, which already exited.

I don't have an idea how to workaround this atm. :disappointed: 

//cc @stefanpenner

**Comment by stefanpenner** [comment]
ahh, can we pull in someone from the chocolatey team?

**Comment by johanneswuerbach** [comment]
Maybe @ferventcoder or @Iristyle? Is there a way to keep the shim running and kill the tree?

**Comment by ferventcoder** [comment]
Help me understand what you want to do. It sounds like this tool should kill phantomjs.exe (the actual, not the shim). The shim should be blocking until phantomjs shuts down.

**Comment by ferventcoder** [comment]
I'm guessing you kill the shim and you want to kill the entire tree. I think you already stated that.

As you can see here the shim is blocking. It won't exit on it's own until the phantomjs.exe (actual) exits.
image

**Comment by johanneswuerbach** [comment]
Currently I'm sending SIGTERM to the process with the pid I spawned (which I guess is the shim). This seems to kill the shim, but not phantomjs. When I'm installing phantomjs manually or use 1.9.8 this works as expected.

**Comment by ferventcoder** [comment]
I wonder if we can enhance shims that receive a SIGTERM to destroy the tree? That seems like a much better option.

**Comment by ferventcoder** [comment]
I created https://github.com/chocolatey/shimgen/issues/11 to handle this.

**Comment by johanneswuerbach** [comment]
That sounds great. Here is a small example script to reproduce the issue:
```js
var cp = require('child_process');
var p = cp.spawn('phantomjs', ['--webdriver=8910'], {}); // The wd arg just keeps phantom listening
p.on('close', function() {
  console.log('Should be called.')
});
setTimeout(function() {
  p.kill();
}, 2000);
```

**Comment by ferventcoder** [comment]
Thanks. I will have something out after a bit.

**Comment by ferventcoder** [comment]
So I can't find a nice way to handle SIGKILL but SIGTERM is going to be in Chocolatey 0.9.9 (you will need to regenerate your shims). It will be out in rc8 (due out this weekend).

**Comment by ferventcoder** [comment]
I take it you are good to go? :)

**Comment by johanneswuerbach** [comment]
Yes, I had to switch from `process.kill` to executing `taskkill /T` on Windows as of https://github.com/airportyh/testem/pull/520 (npm is creating a cmd file when installing phantomjs), which also solves this issue.

**Pull request merged**
